### ISSUE TITLE
Browser is downloading .rdp files instead of opening the session in the browser

### ISSUE THREAD

**Issue by macuco-de** [kimmknight/rdpx#11]
Hi,

i'm testing rdpx v0380 on Windows 10 Pro latest updates.

I got everything running, can create new RemoteApps and also see existing ones. However, if i'm trying to start a session in the browser (chrome and ff), the .rdp file is downloaded instead of executed in the browser.

What am I doing wrong here?

**Comment by kimmknight** [comment]
Hi @macuco-de

Are you using Chrome? If so, click the arrow next to the RDP download, then select "Always open files of this type"

**Comment by macuco-de** [comment]
Hi @kimmknight 

I'm so sorry, I think I misunderstood the intention of your great project. I thought it is an alternative to RD Web Access, showing the Remote Desktop directly in the browser instead of opening the default RD Windows Client. Do you know a project similar to RD Web Access?

However, your project is great. I like it very much. Also your remoteapptool and raweb. You can close the issue.

**Comment by kimmknight** [comment]
No worries, thanks for the feedback @macuco-de 

If you haven't already, I would strongly suggest checking out Apache Guacamole. I think it's what you're looking for and it is works brilliantly!
