### ISSUE TITLE
Hide Main Settings and App Settings

### ISSUE THREAD

**Issue by FawzanAjward** [kimmknight/rdpx#13]
Hello, 

Could you please help me to hide the main settings icon and app settings icons. I am using this program as the main source for hosting apps with rdpwrapper and we are happy with it. But unfortunately users started playing with the settings and ACL is not strong here. I tried playing with the HTML file, CSS and nothing seems to hide the settings. Also could you please guide me to create my own SSL using letsencrypt or certbox using NGINX. I tried several times and no luck. Much appreciated for your wonderful program and contributions and would highly appreicate your prompt response.

**Comment by kimmknight** [comment]
Thanks for the feedback. I'm glad rdpx has been useful to you.

I have been completely rewriting rdpx so I won't be adding any features to this build.

You can however, make this change fairly easily yourself:

Edit `js/ui.js` and find line 24, 25, and 26:

```
24 |    makecard("Full desktop session", "img/desktop.png", "downloadrdp();");
25 |    makecard("New RemoteApp", "img/add.png", "clickcreatenewcard()");
26 |    makecard("Settings", "img/settings.png", "clicksettingscard()");
```

To remove the _Full desktop session_ card, delete line 24.

To remove the _New RemoteApp_ card, delete line 25.

To remove the _settings_ card, delete line 26.

**Comment by FawzanAjward** [comment]
> Refer

Thanks a lot. It really works. Also is there any way to remove the settings for each app, like there is a small setting icon for each new apps? and i am happy to hear that you are working on a new RDPX. you are AWSOME.

**Comment by kimmknight** [comment]
Ah yep, sorry I missed that part of your question.

Also in `js/ui.js` find line 45 - 51 (unless you deleted earlier lines):

```
45 |    if (settingsaction != "") {
46 |        settingshtml = `
47 |            <div class="settingsicon" onclick="${settingsaction}">
48 |                <i class="large material-icons w3-hover-opacity" style="position: absolute;">settings</i>
49 |            </div>
50 |            `.trim();
51 |        };
```

Delete these lines, or comment them out by starting the line with `//`.

**Comment by FawzanAjward** [comment]
Thanks for your hard work and the support. Please let me know how to send some donations to you! Besides could you hook me to any docs or steps to generate the SSL. I tried many times and still havent had the luck to get the SSL.
